# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Cart.destroy_all
CartItem.destroy_all
Item.destroy_all
User.destroy_all


#USER
user1 = User.create(first_name: "Bob", last_name: "Smith", email: "bobs@gmail.com", billing_address: "123 Lovers Lane Austin,TX 78747", shipping_address: "123 Lovers Lane Austin,TX 78747", phone_number: "123-456-7890", password: "Bobs123", username: "Bobs123")
user2 = User.create(first_name: "Avy", last_name: "Pang", email: "apang@gmail.com", billing_address: "123 Austin Avenue Austin,TX 78704", shipping_address: "123 Austin Avenue Austin,TX 78704", phone_number: "123-456-7890", password: "Apang123", username: "Apang123")


#---------------------------------ITEMS-------------------------------------------------------- 
#TOTORO ----------------
#Bedding
totoro1 = Item.create(name: "My Neighborhood Totoro Sleeping Bag", image: "https://images-na.ssl-images-amazon.com/images/I/61Rd9jnw7SL._AC_SL1000_.jpg", category: "Bedding", description: "This portable Futon Matratze is foldable, easy to travel or store, perfect for small apartments and is made of soft and comfortable fabric.", movie: "My Neighbor Totoro", price: "229.99", quantity: 10)
totoro2 = Item.create(name: "My Neighborhood Totoro Linen Throw Pillow Cover", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1125403566_2nd-600x600.jpg", category: "Bedding", description: "These linen pillow covers are one of a kind and machine washable!", movie: "My Neighbor Totoro", price: "9.99", quantity: 10)
#Mug
totoro3 = Item.create(name: "My Neighborhood Totoro Cat Bus Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12012020131207-600x600.jpg", category: "Mug" , description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!" ,movie: "My Neighborhood Totoro", price: "18.00" , quantity: 20)
totoro4 = Item.create(name: "My Neighborhood Totoro By The Moon Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11262020051133-600x600.jpg", category: "Mug" , description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!" ,movie: "My Neighborhood Totoro", price: "18.00" , quantity: 20)
#Face Mask
totoro5 = Item.create(name: "My Neighborhood Totoro by the Moon Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11172020001137-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "My Neighbor Totoro", price: "15.00", quantity: 100)
totoro6 = Item.create(name: "My Neighborhood Totoro Cat Bus and Mei Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11172020001105-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "My Neighbor Totoro", price: "15.00", quantity: 100)
totoro7 = Item.create(name: "My Neighborhood Totoro NNeon Collage Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11172020001112-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "My Neighbor Totoro", price: "15.00", quantity: 100)
#Bag
totoro8 = Item.create(name: "My Neighborhood Totoro Backpack", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage258651716_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "15.95", quantity: 50)
totoro9 = Item.create(name: "My Neighborhood Totoro Coin Purse", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage837022116_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "5.95", quantity: 50)
totoro10 = Item.create(name: "My Neighborhood Totoro Black Backpack", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage204239197_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "25.95", quantity: 50)
totoro11 = Item.create(name: "My Neighborhood Totoro Crossbody Bag", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage169419706_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "15.95", quantity: 50)
totoro12 = Item.create(name: "My Neighborhood Totoro Children Plush Backpack", image: "https://ghibli.store/wp-content/uploads/2020/04/HTB12vTGk77mBKNjSZFyq6zydFXaf_2nd-533x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "15.95", quantity: 50)
totoro13 = Item.create(name: "My Neighborhood Totoro Leather Wallet", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage609104315_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "18.95", quantity: 50)
totoro14 = Item.create(name: "My Neighborhood Totoro Printing Canvas Backpack", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage171713920_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "My Neighbor Totoro" , price: "28.95", quantity: 50)
#Keychain
totoro15 = Item.create(name: "My Neighborhood Totoro Characters Keychain", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage655776400_2nd.jpg", category: "KeyChain", description: "Add this cute accessory to any bag, backpack, purse or keys", movie: "My Neighbor Totoro" , price: "5.99" , quantity: 80 )
#Pin
totoro16 = Item.create(name: "My Neighborhood Totoro Badge Pins Set 6 pcs", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1023504534_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "My Neighbor Totoro" , price: "15.99", quantity: 30)
totoro17 = Item.create(name: "My Neighborhood Totoro Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage474144649_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "My Neighbor Totoro" , price: "9.99", quantity: 30)
totoro18 = Item.create(name: "My Neighborhood Totoro Catbus Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1204586206_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "My Neighbor Totoro" , price: "9.99", quantity: 30)
totoro19 = Item.create(name: "My Neighbor Totoro in Ramen Bowl Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/05/Totoro-pin-badge-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "My Neighbor Toto" , price: "9.99", quantity: 30)
#Apparel
totoro21 = Item.create(name: "My Neighbor Totoro Cat Bus Hoodie" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12012020131223-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "My Neighbor Totoro", price:"29.99" , quantity: 20 )
totoro22 = Item.create(name: "My Neighbor Totoro Cat Bus T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12012020131259-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "My Neighbor Totoro", price:"9.99" , quantity: 20 )
totoro23 = Item.create(name: "My Neighbor Totoro Colorful T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12192020101245-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "My Neighbor Totoro", price:"9.99" , quantity: 20 )
totoro24 = Item.create(name: "My Neighbor Totoro Sketch Sweatshirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12102020051240-10-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "My Neighbor Totoro", price:"29.99" , quantity: 20 )
totoro25 = Item.create(name: "My Neighbor Totoro Giant and Mini Sweatshirt" , image: "https://ghibli.store/wp-content/uploads/2021/01/redirect01012021140146-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "My Neighbor Totoro", price:"19.99" , quantity: 20 )



# item = Item.create(name: "", image: "" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "" , price: "21.99", quantity: 30)
# item = Item.create(name: "", image: "", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "", price: "$15.00", quantity: 100)
# item = Item.create(name: "", image: "" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "" , price: "9.99", quantity: 30)
# item = Item.create(name: "", image: "" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "" , price: "15.95", quantity: 50)
# item = Item.create(name: "", image: "", category: "KeyChain", description: "Add this cute accessory to any bag, backpack, purse or keys", movie: , price: "5.99" , quantity: 80 )
# item = Item.create(name: "" , image: "", category: "Poster", description: "Personalize your space with this one of a kind Studio Ghibli art!", movie: "", price:"19.99" , quantity: 25 )
# item = Item.create(name: "" , image: "", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "", price:"9.99" , quantity: 20 )
# item = Item.create(name: "" , image: "", category: "Toys", description: "",movie: "", price:"" , quantity: )


#MONONOKE -------------
#Face Mask
mono1 = Item.create(name: "Tree Spirits Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041232.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Princess Mononoke", price: "15.00", quantity: 100)
mono2 = Item.create(name: "Forest Guardian Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041258-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Princess Mononoke", price: "18.00", quantity: 100)
mono3 = Item.create(name: "Ashitaka Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11172020001142-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Princess Mononoke", price: "18.00", quantity: 100)
mono4 = Item.create(name: "Shishigami of the Forest Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020051215-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Princess Mononoke", price: "18.00", quantity: 100)
#Mug
mono6 = Item.create(name: "Princess Mononoke Red Moon Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12052020001202-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
mono7 = Item.create(name: "Princess Mononoke Black and White Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11262020111102-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
mono8 = Item.create(name: "San and The Wolf Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/mockup-44c2c2f3-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
mono9 = Item.create(name: "Forest Guardian Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/mockup-b45881a7-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
mono10 = Item.create(name: "Tree Spirits on the Cherry Blossom Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/mockup-2dd9ef2d-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
mono11 = Item.create(name: "Ashitaka Water Color Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/mockup-6c357f0b-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
mono12 = Item.create(name: "Shishigami of the Forest Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020031233-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Princess Mononoke" , price: "21.99", quantity: 30)
#Apparel
mono14 = Item.create(name: "Wolf Princess Hoodie" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020031202-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"29.99" , quantity: 20)
mono15 = Item.create(name: "Wolf Princess T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020031230-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"19.99" , quantity: 20)
mono16 = Item.create(name: "Ashitaka T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020111224-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono17 = Item.create(name: "Forest Spirit Sweatshirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020061215-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"19.99" , quantity: 20)
mono18 = Item.create(name: "Forst Spirit T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020061227-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono19 = Item.create(name: "Guardians of the Forest Hoodie" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020021247-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"29.99" , quantity: 20)
mono20 = Item.create(name: "Red Moon T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12052020001217-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono21 = Item.create(name: "San and Ashitaka T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020051213-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono22 = Item.create(name: "Shishigai Line Art T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12102020061247-5-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono23 = Item.create(name: "Shishigami of The Forest Hoodie" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020021247-7-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"29.99" , quantity: 20)
mono24 = Item.create(name: "Tree Spirits Sweetshirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12132020051220-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"19.99" , quantity: 20)
mono25 = Item.create(name: "Tree Spirits T-shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12132020051226-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono26 = Item.create(name: "Tree Spirits on the Cherry Blossom" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020021242-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono27 = Item.create(name: "Princess Mononoke and the Broken Mask T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020111218-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"9.99" , quantity: 20)
mono28 = Item.create(name: "Princess Mononoke and the Broken Mask Sweatshirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020111210-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"19.99" , quantity: 20)
mono29 = Item.create(name: "Princess Mononoke Characters T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12062020131258-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Princess Mononoke", price:"19.99" , quantity: 20)


#SPIRITED AWAY ----------
#Mug
spirited1 = Item.create(name: "Haku Dragon and the Bathhouse Classic Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12202020111238-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Spirited Away" , price: "21.99", quantity: 30)
spirited2 = Item.create(name: "The Bathhouse No Face Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12192020101216-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Spirited Away" , price: "21.99", quantity: 30)
spirited3 = Item.create(name: "Haku Dragon with Sen and No Face Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11302020071145-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Spirited Away" , price: "19.99", quantity: 30)
spirited4 = Item.create(name: "The Bathhouse Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12032020121238-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Spirited Away" , price: "19.99", quantity: 30)
spirited5 = Item.create(name: "Susuwatari Graphic Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12212020121252-2-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ponyo" , price: "21.99", quantity: 30)
#Face Mask
spirited6 = Item.create(name: "Spirited Away Characters Compilation Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041255-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps" ,movie: "Spirited Away", price: "15.00", quantity: 20)
spirited7 = Item.create(name: "Spirited Away No Face Tea Time Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11152020041104-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps" ,movie: "Spirited Away", price: "15.00", quantity: 20)
#Pin
spirited8 = Item.create(name: "Spirited Away No Face At Bathhouse Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/05/Spirited-Away-badge-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Spirited Away" , price: "9.99", quantity: 30)
spirited9 = Item.create(name: "Spirted Away No Face, Haku and Chihiro Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/05/No-Face-brooch-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Spirited Away" , price: "9.99", quantity: 30)
spirited10 = Item.create(name: "Spirtied Away No Face and Haku Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/05/No-face-Haku-pin-Spirited-Away-soot-sprite-badge-beautiful-anime-fans-decor-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Spirited Away" , price: "9.99", quantity: 30)
spirited11 = Item.create(name: "Spirited Away Boh Mouse Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1204585696_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Spirited Away" , price: "9.99", quantity: 30)
spirited12 = Item.create(name: "Spirited Away Bathhouse Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1199562581_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Spirited Away" , price: "9.99", quantity: 30)
spirited13 = Item.create(name: "Spirited Away Radish Spirit Badge", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1327078084_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Spirited Away" , price: "9.99", quantity: 30)
#Keychain
spirited14 = Item.create(name: "Spirited Away Soot Sprites Plush Keychain", image: "https://ghibli.store/wp-content/uploads/2020/04/HTB1P3p_Kb1YBuNjSszeq6yblFXaz_2nd.jpg", category: "KeyChain", description: "Add this cute accessory to any bag, backpack, purse or keys", movie: "Spirited Away", price: "5.99" , quantity: 80)
#Apparel
spirited15 = Item.create(name: "No Face Hoodie", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12022020111221-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Spirited Away", price:"29.99" , quantity: 20)
spirited16 = Item.create(name: "No Face T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12022020111200-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Spirited Away", price:"9.99" , quantity: 20)
spirited17 = Item.create(name: "No Face SweatShirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12022020111251-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Spirited Away", price:"19.99" , quantity: 20 )
spirited18 = Item.create(name: "No Face Eat Whatever You Want Hoodie", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12142020121227-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Spirited Away", price:"29.99" , quantity: 20)
spirited19 = Item.create(name: "No Face Eat Whatever You Want Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12142020121200-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Spirited Away", price:"19.99" , quantity: 20)
spirited20 = Item.create(name: "No Face Eat Whatever You Want T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12142020121211-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Spirited Away", price:"9.99" , quantity: 20)



#HOWLS CASTLE ---------------------
#Mug
howl1 = Item.create(name: "Calcifer Loves Ramen Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12132020051232.jpg" , category: "Mug" , description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  The white gloss is decorated with a full wrap dye sublimation of Califer enjoying his favorite meal!" ,movie: "Howl's Moving Castle", price: "19.95" , quantity: 25)
howl2 = Item.create(name: "Howl's Moving Castle Sketch Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12122020091214-600x600.jpg" , category: "Mug" , description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  The white gloss is decorated with a full wrap dye sublimation of Califer enjoying his favorite meal!" ,movie: "Howl's Moving Castle", price: "19.95" , quantity: 25)
howl3 = Item.create(name: "Howl and Sophia Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11252020021151-600x600.jpg" , category: "Mug" , description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  The white gloss is decorated with a full wrap dye sublimation of Califer enjoying his favorite meal!" ,movie: "Howl's Moving Castle", price: "19.95" , quantity: 25)
#Pin
howl4 = Item.create(name: "Calcifer with Log Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/Hf5df6e52e8654ca8b48819b30d0f45a58_2nd.jpg" , category: "Pin", description: "This badge pin can be used on backpacks, purses, clothing and just about any fabric!", movie: "Howl's Moving Castle" , price: "9.99", quantity: 30)
howl5 = Item.create(name: "Kakashi no Kabu Hanging Clothes Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1327081784_2nd.jpg" , category: "Pin", description: "This badge pin can be used on backpacks, purses, clothing and just about any fabric!", movie: "Howl's Moving Castle" , price: "9.99", quantity: 30)
howl6 = Item.create(name: "Howl and Calcifer Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1149153666_2nd-600x600.jpg" , category: "Pin", description: "This badge pin can be used on backpacks, purses, clothing and just about any fabric!", movie: "Howl's Moving Castle" , price: "9.99", quantity: 30)
#Face Mask
howl7 = Item.create(name: "Howl and Sophia Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041225-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Howl's Moving Castle", price: "15.00", quantity: 100)
howl8 = Item.create(name: "Howl's Castle in Black and White", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041200-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Howl's Moving Castle", price: "15.00", quantity: 100)
howl9 = Item.create(name: "Calcifer Loves Ramen Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041202-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Howl's Moving Castle", price: "15.00", quantity: 100)
howl10 = Item.create(name: "Howl and Sophia Japanese with Characters Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11252020021156-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Howl's Moving Castle", price: "15.00", quantity: 100)
howl11 = Item.create(name: "Howl's Moving Castle Sketch Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11242020061125-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Howl's Moving Castle", price: "15.00", quantity: 100)
#Poster
howl12 = Item.create(name: "Howl's Moving Castle Silk Poster", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage170140978_2nd-600x600.jpg", category: "Poster", description: "Personalize your space with this one of a kind Studio Ghibli art!", movie: "", price:"19.99" , quantity: 25 )
howl13 = Item.create(name: "Howl's Moving Castle Classic Poster", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage263913121_2nd-600x600.jpg", category: "Poster", description: "Personalize your space with this one of a kind Studio Ghibli art!", movie: "", price:"19.99" , quantity: 25 )
howl14 = Item.create(name: "Howl's Moving Castle Movie Paper Poster", image: "https://ghibli.store/wp-content/uploads/2020/05/TIE-LER-Anime-Howl-Moving-Castle-Classic-Nostalgia-Kraft-Paper-Cafe-Bar-Poster-Retro-Wall-Sticker-1-600x600.jpg", category: "Poster", description: "Personalize your space with this one of a kind Studio Ghibli art!", movie: "Howl's Moving Castle", price:"19.99" , quantity: 25)
#Apparel
howl15 = Item.create(name: "Howl's Castle in Black and White Sweatshirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12132020071213-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material i high-stretch and machine washable.",movie: "Howl's Moving Castle", price:"19.99" , quantity: 20 )
howl16 = Item.create(name: "Howl's Castle in Black and White T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12132020071224-2-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Howl's Moving Castle", price:"19.99" , quantity: 20)
howl17 = Item.create(name: "Calcifer Loves Ramen Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12132020041209-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Howl's Moving Castle", price:"9.99" , quantity: 20)
howl18 = Item.create(name: "Howl's Moving Castle Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12262020131229-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Howl's Moving Castle", price:"19.99" , quantity: 20)
howl19 = Item.create(name: "Howl's Moving Castle Color T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12232020111239-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Howl's Moving Castle", price:"9.99" , quantity: 20)
howl20 = Item.create(name: "Howl's Moving Castle Sketch T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12122020091247-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Howl's Moving Castle", price:"9.99" , quantity: 20)



#KIKI'S DELIVERY---------------------
#Mug
kiki1 = Item.create(name: "Kiki's Delivery Service 30th Anniversary Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11272020041120.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  It is beautifully decorated with full wrap dye sublimation of your favorite witch!",movie: "Kiki's Delivery Service", price: "20.00", quantity: 10)
kiki2 = Item.create(name: "Kiki's The Best Witch Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12122020091211.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  It is beautifully decorated with full wrap dye sublimation of your favorite witch!",movie: "Kiki's Delivery Service", price: "20.00", quantity: 10)
#Face Mask
kiki3 = Item.create(name: "Kiki's Delivery Service 30th Anniversary Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11212020091136-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Kiki's Delivery Service", price: "15.00", quantity: 100)
kiki4 = Item.create(name: "Jiji & Pancake Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11212020091124-1-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Kiki's Delivery Service", price: "15.00", quantity: 100)
#Apparel
kiki5 = Item.create(name: "Kiki's and Tombo Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12112020141258-1.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Kiki's Delivery Service", price:"9.99" , quantity: 20)
kiki6 = Item.create(name: "Kiki The Best Witch T-shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12122020081242-1.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Kiki's Delivery Service", price:"9.99" , quantity: 20)
kiki7 = Item.create(name: "" , image: "", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Kiki's Delivery Service", price:"9.99" , quantity: 20 )




#PONYO-------------------------------
#Mug
ponyo1 = Item.create(name: "Ponyo On The Cliff By The Sea Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11282020101113-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ponyo" , price: "21.99", quantity: 30)
ponyo2 = Item.create(name: "Ponyo By The Sea Classic Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020111240-9-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ponyo" , price: "21.99", quantity: 30)
#Face Mask
ponyo3 = Item.create(name: "Ponyo and Sosuke Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041235.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ponyo", price: "15.00", quantity: 100)
ponyo4 = Item.create(name: "Ponyo On The Cliff By The Sea Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11282020101111-5-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ponyo", price: "15.00", quantity: 100)
ponyo5 = Item.create(name: "Ponyo Very First Trip Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12082020041258-2-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ponyo", price: "15.00", quantity: 100)
ponyo6 = Item.create(name: "Ponyo On The Waves Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11152020041108-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ponyo", price: "15.00", quantity: 100)
#Poster
ponyo8 = Item.create(name: "Ponyo On The Cliff Wall Canvas" , image: "https://ghibli.store/wp-content/uploads/2020/11/Modern-Home-Decoration-Wall-Art-Painting-Ponyo-Japanese-Canvas-Pictures-Printing-Nordic-Modular-Artwork-Poster-For-600x600.jpg", category: "Poster", description: "Personalize your space with this one of a kind Studio Ghibli art!", movie: "Ponyo", price:"19.99", quantity: 25)
#Pin
ponyo10 = Item.create(name: "Ponyo On The Cliff Badge Pin", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1017743892_2nd-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Ponyo" , price: "9.99", quantity: 30)
#Apparel
ponyo11 = Item.create(name: "Ponyo and Sasuke Cutout Classic Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12182020131258-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"19.99" , quantity: 20 )
ponyo12 = Item.create(name: "Ponyo and Sasuke Cutout Classic T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12182020131214-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"9.99" , quantity: 20 )
ponyo13 = Item.create(name: "Ponyo ans Sasuke Create Art Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020011235-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"19.99" , quantity: 20 )
ponyo14 = Item.create(name: "Ponyo ans Sasuke Create Art T-shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12162020011237-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"9.99" , quantity: 20 )
ponyo15 = Item.create(name: "Ponyo and Sosuke Sketch Sweatshirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12022020011250-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"19.99" , quantity: 20 )
ponyo16 = Item.create(name: "Ponyo and Sosuke Sketch T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12022020011254-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"9.99" , quantity: 20 )
ponyo17 = Item.create(name: "Ponyo By The Sea Classic T-Shirt", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12172020111243-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"9.99" , quantity: 20 )
ponyo18 = Item.create(name: "Ponyo Loves Ham T-Shirt" , image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12102020081230-1-600x600.jpg", category: "Apparel", description: "Show off your favorite Studio Ghibli film with this brand new item!  The material is high-stretch and machine washable.",movie: "Ponyo", price:"9.99" , quantity: 20 )


#GHIBLI----------------------------------
#Mug
ghibli1 = Item.create(name: "Ghibli Bunch Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12012020231247-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ghibli" , price: "21.99", quantity: 30)
ghibli2 = Item.create(name: "Studio Ghibli Characters As Hogwarts House Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/mockup-23b1d223-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ghibli" , price: "21.99", quantity: 30)
ghibli3 = Item.create(name: "Studio Ghibli Hayao Miyazaki With His Arts Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/mockup-e08e68a4-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ghibli" , price: "21.99", quantity: 30)
ghibli4 = Item.create(name: "Studio Ghibli Circle Mug", image: "https://ghibli.store/wp-content/uploads/2021/01/redirect01082021140158-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ghibli" , price: "21.99", quantity: 30)
ghibli5 = Item.create(name: "Compilation Characters of Studio Ghibli Mug", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11272020131107.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ghibli" , price: "21.99", quantity: 30)
ghibli6 = Item.create(name: "Elemental Studio Ghibli Mug", image: "https://ghibli.store/wp-content/uploads/2020/12/redirect12052020001202-2-600x600.jpg" , category: "Mug", description: "This is a high quality ceramic mug that is both dishwasher and microwave safe.  This mug is beautifully decorated with full wrap dye sublimation with an original design!", movie: "Ghibli" , price: "21.99", quantity: 30)
#Face Mask
ghibli7 = Item.create(name: "Stay Home and Watch Ghibli Movie Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11242020061104-600x600.jpg", category: "Face Mask" , description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps" ,movie: "Ghibli" , price: "12.00" , quantity: 50 )
ghibli8 = Item.create(name: "Studio Ghbili Characters As Hogwarts House Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11242020061153-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ghibli", price: "15.00", quantity: 100)
ghibli9 = Item.create(name: "8 BIT Ghibli Adventures Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11152020041109-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ghibli", price: "15.00", quantity: 100)
ghibli10 = Item.create(name: "Studio Ghibli Logo Face Mask", image: "https://ghibli.store/wp-content/uploads/2020/11/redirect11152020041127-600x600.jpg", category: "Face Mask", description: "Lightweight & ultra-breathable two-layer protective face mask with black soft stretch ear straps", movie: "Ghibli", price: "15.00", quantity: 100)
#Bag
ghibli11 = Item.create(name: "Studio Ghibli Drawstring Bags", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage840305189_2nd.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "Ghibli" , price: "$15.95", quantity: 50)
ghibli12 = Item.create(name: "Studio Ghibli Kawaii Coin Purse", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage712107723_2nd-600x600.jpg" , category: "Bag" , description: "Carry your belongings in Ghibli Style!" ,movie: "Ghibli" , price: "$15.95", quantity: 50)
#Pin
ghibli13 = Item.create(name: "Studio Ghibli Characters Cute Badge Pins", image: "https://ghibli.store/wp-content/uploads/2020/05/P3169-Dongmanli-Anime-Specter-Mask-Metal-Enamel-Pins-and-Brooches-for-Women-Men-Lapel-Pin-Bags-wpp1589453907419-600x600.jpg" , category: "Pin", description: "Show off this badge pin on backpacks, purses, clothing and just about any fabric!", movie: "Ghibli" , price: "19.99", quantity: 30)
#Bedding
ghibli14 = Item.create(name: "My Neighborhood Totoro Ghibli Characters Linen Throw Pillow Cover", image: "https://ghibli.store/wp-content/uploads/2020/04/productimage1125403566_2nd-600x600.jpg", category: "Bedding", description: "These linen pillow covers are one of a kind and machine washable!", movie: "Ghibli", price: "9.99", quantity: 10)


#---------------------------------------------------------------------------------
#CART
cart1 = Cart.create(user_id: User.first.id, purchase: false)
cart2 = Cart.create(user_id: User.second.id, purchase: false)

#CART_ITEM
cart_item1 = CartItem.create(cart_id: Cart.first.id, item_id: Item.first.id)
cart_item2 = CartItem.create(cart_id: Cart.second.id, item_id: Item.second.id)

